# ---------------------------------------------------------------
# Programmer(s): Cody J. Balos @ LLNL
# ---------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2025-2026, Lawrence Livermore National Security,
# University of Maryland Baltimore County, and the SUNDIALS contributors.
# Copyright (c) 2013-2025, Lawrence Livermore National Security
# and Southern Methodist University.
# Copyright (c) 2002-2013, Lawrence Livermore National Security.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# ---------------------------------------------------------------
# SUNDIALS build options that are interpreted after all other
# CMake configuration.
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Option to use specialized fused kernels in the packages. Currently only
# available in CVODE.
# ---------------------------------------------------------------

if(SUNDIALS_ENABLE_CUDA OR SUNDIALS_ENABLE_HIP)
  set(CUDA_OR_HIP TRUE)
else()
  set(CUDA_OR_HIP FALSE)
endif()

sundials_option(
  SUNDIALS_ENABLE_PACKAGE_FUSED_KERNELS BOOL
  "Enable specialized fused GPU kernels" OFF
  DEPENDS_ON SUNDIALS_ENABLE_CVODE CUDA_OR_HIP
  DEPENDS_ON_THROW_ERROR DEPRECATED_NAMES SUNDIALS_BUILD_PACKAGE_FUSED_KERNELS)

# ---------------------------------------------------------------
# Options to enable/disable build for NVECTOR modules.
# ---------------------------------------------------------------

# required modules are in the build list, but cannot be disabled
set(SUNDIALS_ENABLE_NVECTOR_SERIAL TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_SERIAL")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_CUDA BOOL
  "Enable the NVECTOR_CUDA module (requires CUDA)" ON
  DEPENDS_ON SUNDIALS_ENABLE_CUDA CMAKE_CUDA_COMPILER
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_CUDA)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_CUDA")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_HIP BOOL
  "Enable the NVECTOR_HIP module (requires HIP)" ON
  DEPENDS_ON SUNDIALS_ENABLE_HIP
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_HIP)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_HIP")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_SYCL BOOL
  "Enable the NVECTOR_SYCL module (requires SYCL)" ON
  DEPENDS_ON SUNDIALS_ENABLE_SYCL
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_SYCL)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_SYCL")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_MANYVECTOR
  BOOL
  "Enable the NVECTOR_MANYVECTOR module"
  ON
  ADVANCED
  DEPRECATED_NAMES
  BUILD_NVECTOR_MANYVECTOR)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_MANYVECTOR")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_MPIMANYVECTOR BOOL
  "Enable the NVECTOR_MPIMANYVECTOR module (requires MPI)" ON
  DEPENDS_ON SUNDIALS_ENABLE_MPI
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_MPIMANYVECTOR)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_MPIMANYVECTOR")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_MPIPLUSX BOOL
  "Enable the NVECTOR_MPIPLUSX module (requires MPI)" ON
  DEPENDS_ON SUNDIALS_ENABLE_MPI SUNDIALS_ENABLE_NVECTOR_MPIMANYVECTOR
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_MPIPLUSX)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_MPIPLUSX")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_PARALLEL BOOL
  "Enable the NVECTOR_PARALLEL module (requires MPI)" ON
  DEPENDS_ON SUNDIALS_ENABLE_MPI
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_PARALLEL)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_PARALLEL")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_OPENMP BOOL "Enable the NVECTOR_OPENMP module" ON
  DEPENDS_ON SUNDIALS_ENABLE_OPENMP
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_OPENMP)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_OPENMP")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_OPENMPDEV BOOL "Enable the NVECTOR_OPENMPDEV module"
  ON
  DEPENDS_ON SUNDIALS_ENABLE_OPENMP_DEVICE OPENMP_SUPPORTS_DEVICE_OFFLOADING
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_OPENMPDEV)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_OPENMPDEV")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_PARHYP BOOL
  "Enable the NVECTOR_PARHYP module (requires hypre)" ON
  DEPENDS_ON SUNDIALS_ENABLE_HYPRE
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_PARHYP)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_PARHYP")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_PETSC BOOL
  "Enable the NVECTOR_PETSC module (requires PETSc)" ON
  DEPENDS_ON SUNDIALS_ENABLE_PETSC
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_PETSC)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_PETSC")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_PTHREADS BOOL "Enable the NVECTOR_PTHREADS module" ON
  DEPENDS_ON SUNDIALS_ENABLE_PTHREAD
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_PTHREADS)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_PTHREADS")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_RAJA BOOL
  "Enable the NVECTOR_RAJA module (requires RAJA)" ON
  DEPENDS_ON SUNDIALS_ENABLE_RAJA
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_RAJA)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_RAJA")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_TRILINOS BOOL
  "Enable the NVECTOR_TRILINOS module (requires Trilinos)" ON
  DEPENDS_ON SUNDIALS_ENABLE_TRILINOS
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_TRILINOS)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_TRILINOS")

sundials_option(
  SUNDIALS_ENABLE_NVECTOR_KOKKOS BOOL
  "Enable the NVECTOR_KOKKOS module (requires Kokkos)" ON
  DEPENDS_ON SUNDIALS_ENABLE_KOKKOS
  ADVANCED DEPRECATED_NAMES BUILD_NVECTOR_KOKKOS)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_NVECTOR_KOKKOS")

# ---------------------------------------------------------------
# Options to enable/disable build for SUNMATRIX modules.
# ---------------------------------------------------------------

# required modules are in the build list, but cannot be disabled
set(SUNDIALS_ENABLE_SUNMATRIX_BAND TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_BAND")
set(SUNDIALS_ENABLE_SUNMATRIX_DENSE TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_DENSE")
set(SUNDIALS_ENABLE_SUNMATRIX_SPARSE TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_SPARSE")

set(_COMPATIBLE_INDEX_SIZE FALSE)
if(SUNDIALS_INDEX_SIZE MATCHES "32")
  set(_COMPATIBLE_INDEX_SIZE TRUE)
endif()
sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_CUSPARSE BOOL
  "Enable the SUNMATRIX_CUSPARSE module (requires CUDA and 32-bit indexing)" ON
  DEPENDS_ON SUNDIALS_ENABLE_CUDA CMAKE_CUDA_COMPILER _COMPATIBLE_INDEX_SIZE
             SUNDIALS_ENABLE_NVECTOR_CUDA
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_CUSPARSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_CUSPARSE")

sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_GINKGO BOOL
  "Enable the SUNMATRIX_GINKGO module (requires Ginkgo)" ON
  DEPENDS_ON SUNDIALS_ENABLE_GINKGO
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_GINKGO)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_GINKGO")

sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_KOKKOSDENSE BOOL
  "Enable the SUNMATRIX_KOKKOSDENSE module" ON
  DEPENDS_ON SUNDIALS_ENABLE_KOKKOS SUNDIALS_ENABLE_KOKKOS_KERNELS
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_KOKKOSDENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_KOKKOSDENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_MAGMADENSE BOOL
  "Enable the SUNMATRIX_MAGMADENSE module (requires MAGMA)" ON
  DEPENDS_ON SUNDIALS_ENABLE_MAGMA
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_MAGMADENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_MAGMADENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_ONEMKLDENSE BOOL
  "Enable the SUNMATRIX_ONEMKLDENSE module (requires oneMKL)" ON
  DEPENDS_ON SUNDIALS_ENABLE_ONEMKL
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_ONEMKLDENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_ONEMKLDENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNMATRIX_SLUNRLOC BOOL
  "Enable the SUNMATRIX_SLUNRLOC module (requires SuperLU_DIST)" ON
  DEPENDS_ON SUNDIALS_ENABLE_SUPERLUDIST
  ADVANCED DEPRECATED_NAMES BUILD_SUNMATRIX_SLUNRLOC)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNMATRIX_SLUNRLOC")

# ---------------------------------------------------------------
# Options to enable/disable build for SUNLINSOL modules.
# ---------------------------------------------------------------

# required modules are in the build list, but cannot be disabled
set(SUNDIALS_ENABLE_SUNLINSOL_BAND TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_BAND")
set(SUNDIALS_ENABLE_SUNLINSOL_DENSE TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_DENSE")
set(SUNDIALS_ENABLE_SUNLINSOL_PCG TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_PCG")
set(SUNDIALS_ENABLE_SUNLINSOL_SPBCGS TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SPBCGS")
set(SUNDIALS_ENABLE_SUNLINSOL_SPFGMR TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SPFGMR")
set(SUNDIALS_ENABLE_SUNLINSOL_SPGMR TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SPGMR")
set(SUNDIALS_ENABLE_SUNLINSOL_SPTFQMR TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SPTFQMR")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_CUSOLVERSP BOOL
  "Enable the SUNLINSOL_CUSOLVERSP module (requires CUDA and 32-bit indexing)"
  ON
  DEPENDS_ON SUNDIALS_ENABLE_CUDA CMAKE_CUDA_COMPILER
             SUNDIALS_ENABLE_NVECTOR_CUDA SUNDIALS_ENABLE_SUNMATRIX_CUSPARSE
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_CUSOLVERSP)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_CUSOLVERSP")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_GINKGO BOOL
  "Enable the SUNLINSOL_GINKGO module (requires Ginkgo)" ON
  DEPENDS_ON SUNDIALS_ENABLE_GINKGO
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_GINKGO)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_GINKGO")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_KLU BOOL
  "Enable the SUNLINSOL_KLU module (requires KLU)" ON
  DEPENDS_ON SUNDIALS_ENABLE_KLU
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_KLU)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_KLU")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_KOKKOSDENSE BOOL
  "Enable the SUNLINSOL_KOKKOSDENSE module" ON
  DEPENDS_ON SUNDIALS_ENABLE_KOKKOS SUNDIALS_ENABLE_KOKKOS_KERNELS
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_KOKKOSDENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_KOKKOSDENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_LAPACKBAND BOOL
  "Enable the SUNLINSOL_LAPACKBAND module (requires LAPACK)" ON
  DEPENDS_ON SUNDIALS_ENABLE_LAPACK
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_LAPACKBAND)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_LAPACKBAND")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_LAPACKDENSE BOOL
  "Enable the SUNLINSOL_LAPACKDENSE module (requires LAPACK)" ON
  DEPENDS_ON SUNDIALS_ENABLE_LAPACK
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_LAPACKDENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_LAPACKDENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_MAGMADENSE BOOL
  "Enable the SUNLINSOL_MAGMADENSE module (requires MAGMA)" ON
  DEPENDS_ON SUNDIALS_ENABLE_MAGMA
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_MAGMADENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_MAGMADENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_ONEMKLDENSE BOOL
  "Enable the SUNLINSOL_ONEMKLDENSE module (requires oneMKL)" ON
  DEPENDS_ON SUNDIALS_ENABLE_ONEMKL
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_ONEMKLDENSE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_ONEMKLDENSE")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_SUPERLUDIST BOOL
  "Enable the SUNLINSOL_SUPERLUDIST module (requires SUPERLUDIST)" ON
  DEPENDS_ON SUNDIALS_ENABLE_SUPERLUDIST SUNDIALS_ENABLE_SUNMATRIX_SLUNRLOC
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_SUPERLUDIST)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SUPERLUDIST")

sundials_option(
  SUNDIALS_ENABLE_SUNLINSOL_SUPERLUMT BOOL
  "Enable the SUNLINSOL_SUPERLUMT module (requires SUPERLUMT)" ON
  DEPENDS_ON SUNDIALS_ENABLE_SUPERLUMT
  ADVANCED DEPRECATED_NAMES BUILD_SUNLINSOL_SUPERLUMT)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNLINSOL_SUPERLUMT")

# ---------------------------------------------------------------
# Options to enable/disable build for SUNNONLINSOL modules.
# ---------------------------------------------------------------

# required modules are in the build list, but cannot be disabled
set(SUNDIALS_ENABLE_SUNNONLINSOL_NEWTON TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNNONLINSOL_NEWTON")
set(SUNDIALS_ENABLE_SUNNONLINSOL_FIXEDPOINT TRUE)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNNONLINSOL_FIXEDPOINT")

sundials_option(
  SUNDIALS_ENABLE_SUNNONLINSOL_PETSCSNES BOOL
  "Enable the SUNNONLINSOL_PETSCSNES module (requires PETSc)" ON
  DEPENDS_ON SUNDIALS_ENABLE_PETSC PETSC_FOUND
  ADVANCED DEPRECATED_NAMES BUILD_SUNNONLINSOL_PETSCSNES)
list(APPEND SUNDIALS_BUILD_LIST "SUNDIALS_ENABLE_SUNNONLINSOL_PETSCSNES")
